Add loading hacks from snesadvance.dat file
MiyooCFW/buildroot pull request #126
Opened 2024-09-15 20:55 UTC by tiopex

Add loading hacks from snesadvance.dat file function from drPocketSnes emu

2024-09-16 17:49 UTC, Apaczer commented
AFAIR the speedhacks may brake/reduce accuracy on some parts (by skipping some CPU cycles), so you would likely want to make it optional. 
BTW there is dynarec code in snes9x2002 which may help with snes9x2005 (see https://git.crowdedwood.com/snes9x2005/commit/?h=asmgfx&id=479872a8d30b092671ed49868748e48830bc36da)

2024-09-16 18:02 UTC, tiopex commented
That's the plan to add an option to the ra settings

2024-09-16 18:53 UTC, Apaczer commented
You should merge here only then and if succed try to push it upstream, some ppl may like it. Considering it hasn't got any signiffact updates in years (last from @jSTE0, cheers!).

2024-09-16 23:28 UTC, jSTE0 commented
Previously discussed in TriForceX/MiyooCFW#479 in the context of snes9x4d and was known to break some games as noted in TriForceX/MiyooCFW#380.

2024-09-17 15:11 UTC, Apaczer requested changes
seems to work 👍  ("Batman Returs" brakes at startup), but you need full core restart (close and launch again).
Anyway I'm going offline for a month (✈️ ), so this will be my last request.

2024-09-17 15:11 UTC, Apaczer commented on package/libretro-snes9x2002/0002-Add-snesadvance.patch
> ++	sprintf(str,"%s/snesadvance.dat","/mnt/.retroarch/system/snes9x2002");
if you want to specify system dir use maybe ifdef __LIBRETRO__ and just call RETRO_ENVIRONMENT_GET_SYSTEM_DIRECTORY to make it look cleaner

2024-10-12 19:27 UTC, Apaczer approved these changes
Normally this shouldn't be enabled by default, so I will leave merging to you 😏

2024-10-14 17:03 UTC, tiopex commented
Done

2024-10-14 19:10 UTC, merged

2024-10-14 19:10 UTC, Apaczer commented
GJ on this one