Maximize build space for `build-image-uclibc` and `build-image-musl`
MiyooCFW/buildroot pull request #46
Opened 2023-10-20 15:26 UTC by takano32

Maximize build space for `build-image-uclibc` and `build-image-musl`

This'll fix `No space left on device` errors in `MiyooCFW` GitHub Actions.

e.g. https://github.com/TriForceX//actions/runs/6505699465

After Mergine this PR and update submodules in main project.

Thank you.

2023-10-20 19:12 UTC, Apaczer requested changes
Great. I forgot about actions marketplace entirely, thanks for reminder! 

The more sophisticated seems [free-disk-space](https://github.com/marketplace/actions/free-disk-space-ubuntu) which doesn't violete any dependencies upon removal with `rm -rf`, also we could get rid off "$AGENT_TOOLSDIRECTORY" and maybe `/usr/local/share/boost`?

2023-10-20 19:12 UTC, Apaczer commented on .github/workflows/build.yml
> +      uses: easimon/maximize-build-space@master
use latest stable release, for this action it's `@v8`

2023-10-20 19:12 UTC, Apaczer commented on .github/workflows/build.yml
> +      uses: easimon/maximize-build-space@master
`@master` -> `@v8`

2023-10-20 20:57 UTC, takano32 commented
Thanks for your reply.

I commit using stable version of `maximize-build-space`.

But I'm sorry for not familiar with this job is doing what.

> The more sophisticated seems [free-disk-space](https://github.com/marketplace/actions/free-disk-space-ubuntu) which doesn't violete any dependencies upon removal with rm -rf, also we could get rid off "$AGENT_TOOLSDIRECTORY" and maybe /usr/local/share/boost?

I can't understand about above, but `free-disk-space` seems more sophisticated if passed build with it.

Please wait a couple of days or weeks, I'll try this.

Or I haven't caught up with my understanding of how this job works entirely, but if it looks ok, I would consider having it merged once and making changes. Essentially, my goal is to get it to pass upstream testing.

The latter half of the text was so tired that it became a machine translation. My apologies.

Thank you.

2023-10-20 21:02 UTC, takano32 commented on .github/workflows/build.yml
> +      uses: easimon/maximize-build-space@master
Thanks, fixed by this commit. 4c6be325575b20e8755c19d67cbcd3ea395097de

2023-10-20 21:02 UTC, takano32 commented on .github/workflows/build.yml
> +      uses: easimon/maximize-build-space@master
Thanks, fixed by this commit. 4c6be325575b20e8755c19d67cbcd3ea395097de

2023-10-21 11:47 UTC, Apaczer approved these changes

2023-10-21 11:51 UTC, merged