[PACKAGE] Update kernel to 4.14.330
MiyooCFW/buildroot pull request #60
Opened 2023-11-27 11:17 UTC by tiopex

Use latest kernel 4.14.330 from https://www.kernel.org/ + miyoo patches

the updated kernel supports some new features e.g exFat

2023-11-27 17:28 UTC, Apaczer requested changes
:+1: Should we switch next to exFAT ? In future prospect I believe there could be [kernel 5.4](https://github.com/aodzip/buildroot-tiny200/blob/21de5725e119bece421236635a7815fe53aad532/board/widora/mangopi/r3/widora_mangopi_r3_defconfig#L45) support (aodzip have added even CedarX driver in his tree)

2023-11-27 17:28 UTC, Apaczer commented on board/miyoo/kernel/0001-miyoo.patch
I like the idea, but maintaining/commiting kernel changes on a one big patch file will be a pain. Of course that's not an issue if you're working alone on a project

2023-11-27 17:28 UTC, Apaczer commented on configs/miyoo_musl_defconfig
> +BR2_LINUX_KERNEL_CUSTOM_TARBALL=y
I understand you want to speed up build speed, but I would rather see grabing tarbal from cdn.kernel & then maybe grabing patch from our miyoocfw/kernel repo to apply.

Why won't you just rebase from 4.14.330 on our kernel and then add another diff commit on top with miyoo changes - for the sake of time. Might be wise to do it in PR to see what's happend. Lastly I would archive old kernel on another branch.

2023-11-27 18:01 UTC, tiopex commented
> 👍 Should we switch next to exFAT ? In future prospect I believe there could be [kernel 5.4](https://github.com/aodzip/buildroot-tiny200/blob/21de5725e119bece421236635a7815fe53aad532/board/widora/mangopi/r3/widora_mangopi_r3_defconfig#L45) support (aodzip have added even CedarX driver in his tree)

Yes, switch to exfat and mount with sync 0, which should allow to switch off handheld without safe shutdown.

I have also working 4.19.x, tried also 5.4 but not booting, video drivers not working, audio driver cause panic and reset loop. Only backlight drivers works, the rest is unknown, so migrating to 5.4 will be problematic

2023-11-27 18:38 UTC, tiopex commented on configs/miyoo_musl_defconfig
> +BR2_LINUX_KERNEL_CUSTOM_TARBALL=y
Ok, I will rebase our kernel to 4.14.330

2023-11-28 13:28 UTC, closed without merging

2023-11-28 22:20 UTC, Apaczer commented
What hold you to migrate to 4.19.x ?

2023-11-29 06:34 UTC, tiopex commented
> What hold you to migrate to 4.19.x ?

Video is not stable. Sometimes not starting correctly

2023-11-29 13:35 UTC, Apaczer commented
https://github.com/torvalds/linux/commit/b9d1e2e6265f5dc25e9f5dbfbde3e53d8a4958ac

Looks like exFAT has been added starting from 5.7
 I like the idea of sync 0 (was thinking of some periodic sync from daemon or main otherwise), maybe we could patch those changes in our 4.14?

2023-11-29 13:47 UTC, tiopex commented
> [torvalds/linux@b9d1e2e](https://github.com/torvalds/linux/commit/b9d1e2e6265f5dc25e9f5dbfbde3e53d8a4958ac)
> 
> Looks like exFAT has been added starting from 5.7 I like the idea of sync 0 (was thinking of some periodic sync from daemon or main otherwise), maybe we could patch those changes in our 4.14?

weird https://www.kernelconfig.io/config_exfat_fs

anyway, I've managed kernel 5.4.x working which have exfat in staging